# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KVXEY9HNH7IERvOVd2YzWbdEvIY53f6U
"""

import matplotlib.pyplot as plt

def x(y):
    return 0.25 + (.25*y)
def y(x, z):
  return 0.25 + (0.25*x) + (0.25*z)
def z(y, w):
    return .25 + (.25*y) + (.25*w)
def w(z):
    return .25 + (.25*z)
def Seidel():
  print("\nPrograma de Gauss Seidel:")
  print("Ejecutando codigo...\n")
  g2()

def g2():
  
 
  x1 = [0]
  x2= [0]
  x3 = [0]
  x4 = [0]
  i=0
  
  while(i < 10):
    
      x1.append(x(x2[i]))
      x2.append(y(x1[i+1],x3[i]))
      x3.append(z(x2[i+1],x4[i]))
      x4.append(w(x3[i+1])) 
      i+=1
    
    
  print("x: " +str(x1))
  print("\ny: " +str(x2))
  print("\nz: " +str(x3))
  print("\nw: " +str(x4))
  plt.plot(x1, label = "x_RES")
  plt.plot(x2, label = "y_RES")
  plt.plot(x3, label = "z_RES")
  plt.plot(x4, label = "w_RES")
  plt.legend()
  plt.show() 
  

Seidel()